namespace Stackworx.EfCoreGraphQL;

using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Stackworx.EfCoreGraphQL.Abstractions;
using Stackworx.EfCoreGraphQL.Shared;

public static class DataLoaderGenerator
{
    public static async Task Generate(
        DbContext dbContext,
        string outPath,
        Mode? mode = Mode.OptOut,
        // Some types cannot be annotated and need to be manually excluded
        // E.g. Identity types
        Func<IEntityType, bool>? filter = null,
        string? ns = "Generated.DataLoaders")
    {
        var model = dbContext.Model;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("//  Source: EF Core model navigations");
        sb.AppendLine("//  Style: HotChocolate [DataLoader] decorator methods");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using HotChocolate;");
        sb.AppendLine("using GreenDonut;");
        sb.AppendLine("using HotChocolate.Types;");
        sb.AppendLine();

        foreach (var entity in model.GetEntityTypes()
                     .Where(e => !e.IsOwned())
                     .OrderBy(e => e.Name))
        {
            if (entity.ShouldIgnore())
            {
                continue;
            }

            if (mode == Mode.OptIn && !entity.ShouldInclude())
            {
                continue;
            }

            // Allow user to manually exclude specific entities
            if (filter is not null && filter(entity))
            {
                continue;
            }
            
            Generate(dbContext, entity, sb);
        }
        
        await File.WriteAllTextAsync(outPath, sb.ToString());
    }

    private static void Generate(DbContext dbContext, IEntityType entity, StringBuilder sb)
    {
        // Skip join tables
        var pk = entity.FindPrimaryKey();
        if (pk is null)
        {
            return;
        }

        if (pk.Properties.Count > 1)
        {
            return;
        }

        sb.AppendLine($"// {entity.DisplayName()}");
        sb.AppendLine($"[ExtendObjectType<{TypeUtils.GetNestedQualifiedName(entity.ClrType)}>]");
        sb.AppendLine($"public class {entity.DisplayName()}Extensions");
        sb.AppendLine($"{{");

        if (entity.FindPrimaryKey()?.Properties.Count == 1)
        {
            var dataLoader = DataLoader.FromEntity(dbContext, entity);
            sb.Append(dataLoader.EmitComment());
            sb.AppendLine(dataLoader.Emit());
        }

        foreach (var navigation in entity.GetNavigations()
                     .Where(n => !n.IsEagerLoaded && !n.TargetEntityType.IsOwned())
                     .OrderBy(n => n.Name))
        {
            // TODO: warning about composite keys
            if (navigation.ForeignKey.Properties.Count > 1)
            {
                continue;
            }

            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }

            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                var dataLoader = DataLoader.FromNavigation(dbContext, navigation);
                sb.Append(dataLoader.EmitComment());
                sb.AppendLine(dataLoader.Emit());
            }

            var field = FieldExtension.FromNavigation(dbContext, navigation);
            sb.Append(field.EmitComment());
            sb.AppendLine(field.Emit());
        }

        foreach (var navigation in entity.GetSkipNavigations()
                     .Where(n => !n.IsEagerLoaded)
                     .OrderBy(n => n.Name))
        {
            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }
            
            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                // TODO: emit extension
                var manyToMany = ManyToMany.FromNavigation(dbContext, navigation);
                sb.AppendLine(manyToMany.EmitDataLoader());
                sb.AppendLine(manyToMany.EmitFieldExtension());
            }
        }

        sb.AppendLine($"}}");
        sb.AppendLine();
    }
}