namespace Stackworx.EfCoreGraphQL;

using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

public static class DataLoaderGenerator
{
    public static async Task Generate(DbContext dbContext, string outPath)
    {
        var model = dbContext.Model;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("//  Source: EF Core model navigations");
        sb.AppendLine("//  Style: HotChocolate [DataLoader] decorator methods");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        // TODO: make variable
        sb.AppendLine("namespace Generated.DataLoaders;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using HotChocolate;");
        sb.AppendLine("using GreenDonut;");
        sb.AppendLine("using HotChocolate.Types;");
        sb.AppendLine();

        foreach (var entity in model.GetEntityTypes()
                     .Where(e => !e.IsOwned())
                     .OrderBy(e => e.Name))
        {
            if (entity.HasGraphQLIgnore())
            {
                continue;
            }
            
            Generate(dbContext, entity, sb);
        }
        
        await File.WriteAllTextAsync(outPath, sb.ToString());
    }

    private static void Generate(DbContext dbContext, IEntityType entity, StringBuilder sb)
    {
        // Skip join tables
        var pk = entity.FindPrimaryKey();
        if (pk is null)
        {
            return;
        }

        if (pk.Properties.Count > 1)
        {
            return;
        }

        sb.AppendLine($"// {entity.DisplayName()}");
        sb.AppendLine($"[ExtendObjectType(typeof({TypeUtils.GetNestedQualifiedName(entity.ClrType)}))]");
        sb.AppendLine($"public class {entity.DisplayName()}Extensions");
        sb.AppendLine($"{{");

        if (entity.FindPrimaryKey()?.Properties.Count == 1)
        {
            sb.AppendLine(DataLoader.FromEntity(dbContext, entity).Emit());
        }

        foreach (var navigation in entity.GetNavigations()
                     .Where(n => !n.IsEagerLoaded)
                     .OrderBy(n => n.Name))
        {
            // TODO: warning about composite keys
            if (navigation.ForeignKey.Properties.Count > 1)
            {
                continue;
            }

            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }

            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                sb.AppendLine(DataLoader.FromNavigation(dbContext, navigation).Emit());
            }
            
            sb.AppendLine(FieldExtension.FromNavigation(dbContext, navigation).Emit());
        }

        foreach (var navigation in entity.GetSkipNavigations()
                     .Where(n => !n.IsEagerLoaded)
                     .OrderBy(n => n.Name))
        {
            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }
            
            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                // TODO: emit extension
                var manyToMany = ManyToMany.FromNavigation(dbContext, navigation);
                sb.AppendLine(manyToMany.EmitDataLoader());
                sb.AppendLine(manyToMany.EmitFieldExtension());
            }
        }

        sb.AppendLine($"}}");
        sb.AppendLine();
    }
}